### ISSUE TITLE
Initial Checklist

### ISSUE THREAD

**Issue by kognise** [nyu/AirQuality#1]
Here's just an overview of some of the things I/we have to fix:

- [ ] Mobile friendly graphs on overview tab 
- [x] Only show points from last 24h
- [x] Load past 24h of points initially
- [x] PM5 -> PM10 (?)
- [x] Get a finalized list of everything we're measuring
- [x] straight lines between points (sorry, felix)

Feel free to add to this!

**Comment by caspar** [comment]
Mobile issues with graphs at the bottom of Charizard tab too

**Comment by caspar** [comment]
fixed some low-hanging fruit
